package util

const (
	WALLET_TRANSACTION_ORDER_EXECUTOR_STATUS_EXPIRED    = "expired"
	WALLET_TRANSACTION_ORDER_EXECUTOR_STATUS_OPENED     = "open"
	WALLET_TRANSACTION_ORDER_EXECUTOR_STATUS_CLOSED     = "closed"
	WALLET_TRANSACTION_ORDER_EXECUTOR_STATUS_REGISTERED = "registered"
)

const (
	WALLET_TRANSACTION_TYPE_SELL = "Sell"
	WALLET_TRANSACTION_TYPE_BUY  = "Buy"
)
