FROM ubuntu:latest

RUN apt-get update && apt-get upgrade; apt-get clean
RUN apt-get install -y libdbus-1-3 libdrm2 libgbm1 libnss3 libxkbcommon0 gnupg

RUN useradd apps
RUN mkdir -p /home/apps && chown apps:apps /home/apps

RUN apt-get install -y x11vnc

RUN apt-get install -y xvfb

RUN apt-get install -y fluxbox

RUN apt-get install -y wget

RUN apt-get install -y wmctrl

RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list

RUN apt-get update && apt-get -y install google-chrome-stable

COPY image/bootstrap_node.sh /home/apps/bootstrap.sh
RUN chown -R apps:apps /home/apps
RUN chmod +x /home/apps/bootstrap.sh
RUN chmod 777 /home/apps/bootstrap.sh

RUN apt-get update && \
    apt-get install -y curl && \
    curl -sL https://deb.nodesource.com/setup_14.x | bash - && \
    apt-get install -y nodejs

# Aggiorna npm alla versione più recente
RUN npm install -g npm

WORKDIR /home/apps/crawler
COPY package*.json ./
RUN npm ci --production

RUN npx playwright install-deps
#RUN npx playwright install chrome

COPY . /home/apps/crawler
RUN chown -R apps:apps /home/apps

CMD ["bash", "/home/apps/bootstrap.sh"]
